services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    env_file:
      - .env   # Link to the .env file for environment variable resolution
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
