services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $(MARIADB_ROOT_PASSWORD)
      MARIADB_DATABASE: $(MARIADB_DATABASE)moneytracker
      MARIADB_USER: $(MARIADB_USER)
      MARIADB_PASSWORD: $(MARIADB_PASSWORD)
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
